# Generated by Django 3.2.6 on 2021-08-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('operateur', models.CharField(max_length=5)),
                ('lamb_x_coord', models.IntegerField()),
                ('lamb_y_coord', models.IntegerField()),
                ('gps_x_coord', models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True)),
                ('gps_y_coord', models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True)),
                ('index_lamb_coord', models.CharField(blank=True, max_length=255, null=True)),
                ('availibility_2G', models.BooleanField(default=False, verbose_name='2G availibility')),
                ('availibility_3G', models.BooleanField(default=False, verbose_name='3G availibility')),
                ('availibility_4G', models.BooleanField(default=False, verbose_name='4G availibility')),
            ],
        ),
        migrations.AddIndex(
            model_name='provideravailibility',
            index=models.Index(fields=['index_lamb_coord'], name='provider_pr_index_l_e0a4fa_idx'),
        ),
    ]
