# Generated by Django 3.2.6 on 2021-08-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provideravailibility',
            old_name='operateur',
            new_name='provider_code',
        ),
        migrations.AlterField(
            model_name='provideravailibility',
            name='gps_x_coord',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='provideravailibility',
            name='gps_y_coord',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
