# Generated by Django 3.2.6 on 2021-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20210831_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideravailibility',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
